# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, space-separated, supports relative paths.
# This allows alembic/env.py to locate the application core modules properly.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

[post_write_hooks]
# post_write_hooks allow running formatters like black on generated scripts.

[logging]
# Logging configuration matches standard Python logging config dicts.
default_keys = root,sqlalchemy,alembic

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
datefmt = %H:%M:%S
